### ISSUE TITLE
Preprocessor: `#include "x.h"` should look for x.h in same dir as parent file

### ISSUE THREAD

**Issue by icculus** [icculus/SDL_shader_tools#2]
Regardless of what other include directories were specified.

**Comment by gingerBill** [comment]
Make `#include "x.h"` look relative to the current file. This will reduce confusion as much as possible.

And I would not even bother with `#include <y.h>` but make it something more like `#include "foo:y.h"` where `foo` is a named library collection that the user can easily specify at the beginning. It solves all of the issues with the global `<>` nonsense in C (e.g. no first come first serve searches) and also allows for virtual files & directories which can be resolved in the API for the shader language.

**Comment by icculus** [comment]
> It solves all of the issues with the global <> nonsense in C (e.g. no first come first serve searches) 

Since there are no include paths in the compiler by default, the search path order is entirely dictated by the user (or app, if they are using the API directly instead of the command line tool). They can decide what `<y.h>` gets them, but by default it gets them nothing.

My thinking is keeping `<>` vs `""` is least-surprising, since it's otherwise exactly a C-style preprocessor, but also I could envision a game providing some small toolkit of shader helper functions on the system paths, and letting mods use the local paths for their own files.

But being shaders, I don't think it's going to have the primary problem in the C namespace: programs are largely contained to a single compilation unit (an include is just going to inline code), and there just aren't going to be that many includes, even in a "standard library", so there's not going to be as many chances for confusion.

In fact, your average shader is likely to _never_ use `#include` at all.
